# Generated by Django 5.2.4 on 2025-07-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=64)),
                ('definition_id', models.CharField(max_length=64)),
                ('scans', models.JSONField()),
                ('url', models.URLField(max_length=512)),
                ('path', models.TextField()),
                ('method', models.CharField(max_length=16)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('fix', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('last_found', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
