services:
  snyk_django:
    build: .
    container_name: snyk_django  
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"   # debugpy
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      #DATABASE_ENGINE: ${DATABASE_ENGINE}
      #DATABASE_NAME: ${DATABASE_NAME}
      #DATABASE_USERNAME: ${DATABASE_USERNAME}
      #DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      #DATABASE_HOST: ${DATABASE_HOST}
      #DATABASE_PORT: ${DATABASE_PORT}

    command: >
      python -m debugpy
        --listen 0.0.0.0:5678
        --wait-for-client
        manage.py runserver 0.0.0.0:8000

  #postgres_db:
  #    image: postgres:17
  #    environment:
  #      POSTGRES_DB: ${DATABASE_NAME}
  #      POSTGRES_USER: ${DATABASE_USERNAME}
  #      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #    ports:
  #      - "5432:5432"
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    env_file:
  #      - .env
